# Generated by Django 2.0.13 on 2019-12-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_sensor_farm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='actuator',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensor',
            name='farm_id',
            field=models.IntegerField(),
        ),
    ]
